# Generated by Django 4.2 on 2023-05-07 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExportProfile',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('value', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('progress', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScanningDevice',
            fields=[
                ('device_id', models.CharField(max_length=43, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(43)])),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('done', 'Done')], max_length=7)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCollection',
            fields=[
                ('vc_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(36)])),
                ('barcode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('name', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('directory', models.CharField(max_length=255)),
                ('archive', models.BooleanField(default=True)),
                ('imprep', models.BooleanField(default=True)),
                ('ocr', models.BooleanField(default=True)),
                ('ocr_engine', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('process', models.IntegerField(default=0)),
                ('batchId', models.IntegerField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('create', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_id_of_record', to='api.process')),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.donator')),
                ('export', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_id_of_record', to='api.process')),
                ('export_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exportprofile')),
                ('import_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.importprofile')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_id_of_record', to='api.process')),
                ('preprocess', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preprocess_id_of_record', to='api.process')),
                ('scan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_process_of_record', to='api.process')),
                ('scanning_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scanningdevice')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vc', models.ManyToManyField(to='api.virtualcollection')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='process_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.processtype'),
        ),
        migrations.AddField(
            model_name='process',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='api.record'),
        ),
        migrations.AddField(
            model_name='process',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.state'),
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
